apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    heritage: helm
  name: ad-man-go-ad-man
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-man-go-ad-man
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ad-man-go-ad-man
    spec:
      containers:
      - env:
        - name: BASE_DN
          value: ${BASE_DN}
        - name: DC_URL
          value: ${DC_URL}
        image: builditdigital/go-ad-man:latest
        imagePullPolicy: Always
        name: go-ad-man
        ports:
        - containerPort: 6111
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 96Mi
          requests:
            cpu: 50m
            memory: 48Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
