sonarqubedbvolumes:
  image: builditftorelli/postgresql-ansible:9.6.2
  entrypoint: ['/bin/bash']
  command: ['/bin/bash']
sonarqubedb:
  labels:
    io.rancher.sidekicks: sonarqubedbvolumes
  image: builditftorelli/postgresql-ansible:9.6.2
  container_name: sonardb-ansible-compose
  restart: unless-stopped
  tty: true
  stdin_open: true
  hostname: sonar-db.riglet
  environment:
    - MAIN_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/digitalrig-riglet.git
    - MAIN_REPO_BRANCH=microservices-poc-rancher
    - MAIN_REPO_FOLDER=ec2
    - ROLES_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/dr-scripts.git
    - ROLES_REPO_BRANCH=microservices-poc-rancher
    - ROLES_REPO_FOLDER=roles
    - PLAYBOOKS=../postgresql
    - USER_NAME=fabriziotorelli
    - USER_EMAIL=fabrizio.torelli@wipro.com
    - ANSIBLE_HOSTNAME=postgres
    - HOSTNAME=sonar-db
    - RIGLETDOMAIN=riglet
    - PRESTART_POSTGRES=true
    - POSTGRES_PASSWORD=4n4lys1s
    - POSTGRES_USER=sonarqube
    - POSTGRES_DB=sonarqube
    - POSTGRES_OS_USER=
    - POSTGRES_OS_GROUP=
    - PRIVATE_PUBLIC_KEY_TAR_URL=https://github.com/hellgate75/online-keys/raw/master/20170311/postgres/keys.tar
  ports:
    - ${POSTGRESQLPORT}:5432
  volumes_from:
    - sonarqubedbvolumes
sonarqubevolumes:
  image: builditftorelli/sonarqube-ansible:6.2
  entrypoint: ['/bin/bash']
  command: ['/bin/bash']
sonarqube:
  labels:
    io.rancher.sidekicks: sonarqubevolumes
  links:
    - sonarqubedb:sonar-db.riglet
  image: builditftorelli/sonarqube-ansible:6.2
  container_name: sonarqube-ansible-compose
  restart: unless-stopped
  tty: true
  stdin_open: true
  hostname: sonar.riglet
  environment:
    - MAIN_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/digitalrig-riglet.git
    - MAIN_REPO_BRANCH=microservices-poc-rancher
    - MAIN_REPO_FOLDER=ec2
    - ROLES_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/dr-scripts.git
    - ROLES_REPO_BRANCH=microservices-poc-rancher
    - ROLES_REPO_FOLDER=roles
    - PLAYBOOKS=../sonar
    - USER_NAME=fabriziotorelli
    - USER_EMAIL=fabrizio.torelli@wipro.com
    - USER_CREDENTIALS=
    - ANSIBLE_HOSTNAME=sonar
    - HOSTNAME=sonar
    - RIGLETDOMAIN=riglet
    - PRESTART_SONARQUBE=false
    - POSTSTART_SONARQUBE=false
    - SONARQUBE_JDBC_USERNAME=sonarqube
    - SONARQUBE_JDBC_PASSWORD=4n4lys1s
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db.riglet:5432/sonarqube
    - SONARQUBE_WEB_JVM_OPTS=
    - SONARQUBE_ANSIBLE_DEFINED_CONTEXT_PATH=/sonar
    - RESTART_SONARQUBE_AFTER_ANSIBLE=true
    - PRIVATE_PUBLIC_KEY_TAR_URL=https://github.com/hellgate75/online-keys/raw/master/20170311/sonarqube/keys.tar
  ports:
    - ${SONARPORT}:9000
    - ${SONARLISTENERPORT}:9092
  volumes_from:
    - sonarqubevolumes
nexusvolumes:
  image: builditftorelli/nexus-ansible:oss
  entrypoint: ['/bin/bash']
  command: ['/bin/bash']
nexus:
  labels:
    io.rancher.sidekicks: nexusvolumes
  image: builditftorelli/nexus-ansible:oss
  container_name: nexus-ansible-compose
  restart: unless-stopped
  tty: true
  stdin_open: true
  hostname: nexus.riglet
  environment:
    - MAIN_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/digitalrig-riglet.git
    - MAIN_REPO_BRANCH=microservices-poc-rancher
    - MAIN_REPO_FOLDER=ec2
    - ROLES_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/dr-scripts.git
    - ROLES_REPO_BRANCH=microservices-poc-rancher
    - ROLES_REPO_FOLDER=roles
    - PLAYBOOKS=../nexus
    - USER_NAME=fabriziotorelli
    - USER_EMAIL=fabrizio.torelli@wipro.com
    - USER_CREDENTIALS=
    - ANSIBLE_HOSTNAME=nexus
    - HOSTNAME=nexus
    - RIGLETDOMAIN=riglet
    - PRESTART_NEXUS=false
    - POSTSTART_NEXUS=false
    - RESTART_NEXUS_AFTER_ANSIBLE=true
    - PRIVATE_PUBLIC_KEY_TAR_URL=https://github.com/hellgate75/online-keys/raw/master/20170311/nexus/keys.tar
  ports:
    - ${NEXUSPORT}:8081
  volumes_from:
    - nexusvolumes
jenkinsvolumes:
  image: builditftorelli/jenkins-ansible:2.32.3
  entrypoint: ['/bin/bash']
  command: ['/bin/bash']
jenkins:
  labels:
    io.rancher.sidekicks: jenkinsvolumes
  links:
    - sonarqube:sonar.riglet
    - nexus:nexus.riglet
  image: builditftorelli/jenkins-ansible:2.32.3
  privileged: true
  container_name: jenkins-ansible-compose
  restart: unless-stopped
  tty: true
  stdin_open: true
  hostname: jenkins.riglet
  environment:
    - MAIN_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/digitalrig-riglet.git
    - MAIN_REPO_BRANCH=microservices-poc-rancher
    - MAIN_REPO_FOLDER=ec2
    - ROLES_REPO_URL=git@bitbucket.org:digitalrigbitbucketteam/dr-scripts.git
    - ROLES_REPO_BRANCH=microservices-poc-rancher
    - ROLES_REPO_FOLDER=roles
    - PLAYBOOKS=../jenkins,microservices,microservices-recreate
    - USER_NAME=fabriziotorelli
    - USER_EMAIL=fabrizio.torelli@wipro.com
    - USER_CREDENTIALS=
    - ANSIBLE_HOSTNAME=jenkins
    - HOSTNAME=jenkins
    - RIGLETDOMAIN=riglet
    - PRESTART_JENKINS=false
    - RESTART_JENKINS_AFTER_ANSIBLE=false
    - PRIVATE_PUBLIC_KEY_TAR_URL=https://github.com/hellgate75/online-keys/raw/master/20170311/jenkins/keys.tar
    - PLUGINS_TEXT_FILE_URL=
  ports:
    - ${JENKINSPORT}:8080
    - ${JENKINSJNLPPORT}:50000
  volumes_from:
    - jenkinsvolumes
