apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.alpha.kubernetes.io/storage-class: default
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  labels:
    app: jenkins-jenkins
    chart: jenkins-0.1.14
    heritage: Tiller
    release: jenkins
  name: jenkins-jenkins
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # volumeName: pvc-55eefd05-0f55-11e7-ad03-0a31f40c1a57
