apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-03-22T23:14:44Z
  generation: 1
  labels:
    chart: jenkins-0.1.14
    component: jenkins-jenkins-master
    heritage: Tiller
    release: jenkins
  name: jenkins-jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jenkins-jenkins-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"copy-default-config","image":"builditdigital/jenkins-master:latest","command":["sh","/var/jenkins_config/apply_config.sh"],"resources":{},"volumeMounts":[{"name":"jenkins-config","mountPath":"/var/jenkins_config"},{"name":"jenkins-home","mountPath":"/var/jenkins_home"}],"imagePullPolicy":"Always"}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"copy-default-config","image":"builditdigital/jenkins-master:latest","command":["sh","/var/jenkins_config/apply_config.sh"],"resources":{},"volumeMounts":[{"name":"jenkins-config","mountPath":"/var/jenkins_config"},{"name":"jenkins-home","mountPath":"/var/jenkins_home"}],"imagePullPolicy":"Always"}]'
      creationTimestamp: null
      labels:
        chart: jenkins-0.1.14
        component: jenkins-jenkins-master
        heritage: Tiller
        release: jenkins
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
        image: builditdigital/jenkins-master:latest
        imagePullPolicy: Always
        name: jenkins-jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: jenkins-jenkins
        name: jenkins-config
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-jenkins
