apiVersion: v1
data:
  body-size: 32m
  enable-vts-status: "true"
  hsts-include-subdomains: "false"
  proxy-connect-timeout: "30"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  creationTimestamp: 2017-03-25T00:57:51Z
  name: nginx-int-nginx-lego
  namespace: default
