apiVersion: v1
data:
  mongodb-password: null
  mongodb-root-password: null
kind: Secret
metadata:
  labels:
    app: mongo-staging-mongodb
    chart: mongodb-0.4.8
    heritage: Tiller
    release: mongo-staging
  name: mongo-staging-mongodb
  namespace: default
type: Opaque
