apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"kube-dns","namespace":"kube-system","creationTimestamp":null,"labels":{"k8s-addon":"kube-dns.addons.k8s.io","k8s-app":"kube-dns","kubernetes.io/cluster-service":"true","kubernetes.io/name":"KubeDNS"}},"spec":{"ports":[{"name":"dns","protocol":"UDP","port":53,"targetPort":0},{"name":"dns-tcp","protocol":"TCP","port":53,"targetPort":0}],"selector":{"k8s-app":"kube-dns"},"clusterIP":"100.64.0.10"},"status":{"loadBalancer":{}}}'
  labels:
    k8s-addon: kube-dns.addons.k8s.io
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
spec:
  ports:
  - name: dns
    port: ${KUBE_DNS_PORT}
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: ${KUBE_DNS_PORT}
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
