name: Buildit Kibana
version: 0.0.2-buildit
description: |
  Kibana Buildit component is a qualified and optimized ElasticSearch Data Visualizer
  for Rancher Kubernetes environments.
category: Application
