apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"dns-controller","namespace":"kube-system","creationTimestamp":null,"labels":{"k8s-addon":"dns-controller.addons.k8s.io","k8s-app":"dns-controller","version":"v1.5.2"}},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"dns-controller"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-addon":"dns-controller.addons.k8s.io","k8s-app":"dns-controller","version":"v1.5.2"},"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":"","scheduler.alpha.kubernetes.io/tolerations":"[{\"key\":
      \"dedicated\", \"value\": \"master\"}]"}},"spec":{"containers":[{"name":"dns-controller","image":"kope/dns-controller:1.5.2","command":["/usr/bin/dns-controller","--watch-ingress=false","--dns=aws-route53","--zone=ftorelli.rig3.riglet.io","--zone=*/*","-v=2"],"resources":{"requests":{"cpu":"50m","memory":"50Mi"}}}],"dnsPolicy":"Default","nodeSelector":{"kubernetes.io/role":"master"},"hostNetwork":true}},"strategy":{}},"status":{}}'
  creationTimestamp: 2017-03-22T22:35:48Z
  labels:
    k8s-addon: dns-controller.addons.k8s.io
    k8s-app: dns-controller
    version: v1.5.2
  name: dns-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dns-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key": "dedicated", "value":
          "master"}]'
      creationTimestamp: null
      labels:
        k8s-addon: dns-controller.addons.k8s.io
        k8s-app: dns-controller
        version: v1.5.2
    spec:
      containers:
      - command:
        - /usr/bin/dns-controller
        - --watch-ingress=false
        - --dns=aws-route53
        - --zone=${KUBE_CTRL_ROUT53_ZONE}
        - --zone=*/*
        - -v=2
        image: kope/dns-controller:1.5.2
        imagePullPolicy: IfNotPresent
        name: dns-controller
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: Default
      hostNetwork: true
      nodeSelector:
        kubernetes.io/role: master
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
